src/Entity/Autor.php
<?php

namespace App\Entity;

use App\Repository\AutorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AutorRepository::class)
 */
class Autor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Tipo;

    /**
     * @ORM\ManyToMany(targetEntity=Fondo::class, mappedBy="Autor")
     */
    private $Autores;

    public function __construct()
    {
        $this->Autores = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->Tipo;
    }

    public function setTipo(string $Tipo): self
    {
        $this->Tipo = $Tipo;

        return $this;
    }
 
    /**
     * @return Collection|Fondo[]
     */
    public function getAutores(): Collection
    {
        return $this->Autores;
    }

    public function addAutore(Fondo $autore): self
    {
        if (!$this->Autores->contains($autore)) {
            $this->Autores[] = $autore;
            $autore->addAutor($this);
        }

        return $this;
    }

    public function removeAutore(Fondo $autore): self
    {
        if ($this->Autores->removeElement($autore)) {
            $autore->removeAutor($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nombre ."(". $this->Tipo .")";
    }
}

src/Controller/CatalogoPaginadoController.php
<?php

namespace App\Controller;

use App\Repository\FondoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class CatalogoPaginadoController extends AbstractController
{
    #[Route('/catalogo/paginado/{orderBy}/{page}', 
            name: 'catalogo_paginado', 
            defaults: ['page'=>1, 'orderBy'=>'id']
            )]
    public function index(SessionInterface $session, $page, $orderBy, FondoRepository $repo): Response
    {
        
        $session->set('titulo', 'corrupti');
        

        $itemsPorPagina = $this->getParameter('items_per_page', 10);
        $fondos = $repo->findAllWithAutoresAndEditorialesPaginado($page, $orderBy, $itemsPorPagina);
        
        return $this->render('catalogo_paginado/index.html.twig', [
            'fondos' => $fondos,
            'paginaActual' => $page,
            'orderBy' => $orderBy,
            'numTotalPaginas' => intdiv(count($fondos),$itemsPorPagina)
        ]);
    }
}

templates/catalogo_paginado/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catálogo{% endblock %}

{% block body %}
    <h1>Listado del catálogo</h1>

    <h2>Página: {{paginaActual}} | Ordenar por: {{orderBy}} | Número total de páginas: {{numTotalPaginas}}</h2>

    <div id="paginador">
        {% if paginaActual > 1 %}
            <a href="{{path('catalogo_paginado', {page: paginaActual - 1, orderBy: orderBy} )}}">Pág. anterior</a>
        {% else %}
            <span>Pág. anterior</span>
        {% endif %}
        
        <span>
            {% for numPag in 1..numTotalPaginas %}
                <a href="{{path('catalogo_paginado', {page: numPag, orderBy: orderBy} )}}" {% if numPag == paginaActual %} class="currentPage" {% endif %}>{{ numPag }}</a>
            {% endfor %}
        </span>
        
        {% if paginaActual < numTotalPaginas %}
            <a href="{{path('catalogo_paginado', {page: paginaActual + 1, orderBy: orderBy} )}}">Pág. siguiente</a>
        {% else %}
            <span>Pág. siguiente</span>
        {% endif %}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'id'} )}}">Id</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'titulo'} )}}">{{ 'Titulo' | trans }}</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'isbn'} )}}">Isbn</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'autor'} )}}">{{ 'Autor' | trans }}</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'editorial'} )}}">{{ 'Editorial' | trans }}</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'edicion'} )}}">Edicion</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'publicacion'} )}}">Publicacion</a></th>
                <th><a href="{{path('catalogo_paginado', {page: 1, orderBy: 'categoria'} )}}">{{ 'Categoria' | trans }}</a></th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fondo in fondos %}
            <tr>
                <td>{{ fondo.id }}</td>
                <td>{{ fondo.titulo }}</td>
                <td>{{ fondo.isbn }}</td>
                <td>
                {% for autor in fondo.autores %}
                    <p>{{autor}}</p> 
                {% endfor %}
                </td>
                <td>{{ fondo.editorial }}</td>
                <td>{{ fondo.edicion }}</td>
                <td>{{ fondo.publicacion }}</td>
                <td>{{ fondo.categoria }}</td>
                <td>
                    <a href="{{ path('libro_show', {'id': fondo.id}) }}">show</a>
                    <a href="{{ path('libro_edit', {'id': fondo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <div id="paginador">
        {% if paginaActual > 1 %}
        <a href="{{path('catalogo_paginado', {page: paginaActual - 1, orderBy: orderBy} )}}">Pág. anterior</a>
        {% else %}
        <span>Pág. anterior</span>
        {% endif %}
        <span>
            {% for numPag in 1..numTotalPaginas %}
            <a href="{{path('catalogo_paginado', {page: numPag, orderBy: orderBy} )}}" {% if numPag == paginaActual %} class="currentPage" {% endif %}>{{ numPag }}</a>
            {% endfor %}
        </span>
        {% if paginaActual < numTotalPaginas %}
        <a href="{{path('catalogo_paginado', {page: paginaActual + 1, orderBy: orderBy} )}}">Pág. siguiente</a>
        {% else %}
        <span>Pág. siguiente</span>
        {% endif %}
    </div>

    <a href="{{ path('libro_new') }}">Create new</a>
{% endblock %}