src/Entity/Autor.php
<?php

namespace App\Entity;

use App\Repository\AutorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AutorRepository::class)
 */
class Autor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Tipo;

    /**
     * @ORM\ManyToMany(targetEntity=Fondo::class, mappedBy="Autor")
     */
    private $Autores;

    public function __construct()
    {
        $this->Autores = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->Tipo;
    }

    public function setTipo(string $Tipo): self
    {
        $this->Tipo = $Tipo;

        return $this;
    }
 
    /**
     * @return Collection|Fondo[]
     */
    public function getAutores(): Collection
    {
        return $this->Autores;
    }

    public function addAutore(Fondo $autore): self
    {
        if (!$this->Autores->contains($autore)) {
            $this->Autores[] = $autore;
            $autore->addAutor($this);
        }

        return $this;
    }

    public function removeAutore(Fondo $autore): self
    {
        if ($this->Autores->removeElement($autore)) {
            $autore->removeAutor($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nombre ."(". $this->Tipo .")";
    }
}

src/Controller/LibroController.php
<?php

namespace App\Controller;

use App\Entity\Fondo;
use App\Form\FondoType;
use App\Repository\FondoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\SerializerInterface;
#[Route('/crud-libro')]
class LibroController extends AbstractController
{
    #[Route('/', name: 'libro_index', methods: ['GET'])]
    public function index(SessionInterface $session, FondoRepository $fondoRepository): Response
    {
        $session->set('filters', ['title'=> 'Venecia', 'autor'=>'Reverte']);
        $filters = $session->get('filters');
        print_r($filters) ;
        return $this->render('libro/index.html.twig', [
            'fondos' => $fondoRepository->findAllWithAutoresAndEditoriales(),
        ]);
    }

    #[Route('/new', name: 'libro_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $fondo = new Fondo();
        $form = $this->createForm(FondoType::class, $fondo);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fondo);
            $entityManager->flush();

            $this->addFlash("Info", "Nuevo libro añadido: " . $fondo->getTitulo());

            return $this->redirectToRoute('libro_index');
        }

        return $this->render('libro/new.html.twig', [
            'fondo' => $fondo,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'libro_show', methods: ['GET'])]
    public function show(FondoRepository $fondoRepository,$id): Response
    {

        $fondo = $fondoRepository->find($id);
        if(!$fondo){
            throw $this->createNotFoundException('Este libro no existe');
            throw new NotFoundHttpException('Este libro no existe');
        }
        return $this->render('libro/show.html.twig', [
            'fondo' => $fondo,
        ]);
    }

    #[Route('/{id}/edit', name: 'libro_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fondo $fondo): Response
    {
        $form = $this->createForm(FondoType::class, $fondo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            
            $this->addFlash("Info", "Nuevo libro actualizado: " . $fondo->getTitulo());

            return $this->redirectToRoute('libro_index');
        } 

        return $this->render('libro/edit.html.twig', [
            'fondo' => $fondo,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'libro_delete', methods: ['POST'])]
    public function delete(Request $request, Fondo $fondo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fondo->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fondo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('libro_index');
    }

   
    #[Route('/response/', name: 'response')]
     
    public function getJson(FondoRepository $fondoRepository)
    {
        $fondos = $fondoRepository->findAll();

        $fondosArray = [];

        foreach ( $fondos as $fondo ) {
            $fondoArray = [
                 $fondo->getTitulo(),
                 $fondo->getISBN(),
                 $fondo->getEdicion(),
                 $fondo->getPublicacion(),
                 $fondo->getAutor()
            ];
            $fondosArray[] = $fondoArray;
        }
        $nana = $fondosArray;
        
       
      

        

      
    
      return $nana;
    }
}

templates/libro/_delete_form.html.twig
<form method="post" action="{{ path('libro_delete', {'id': fondo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fondo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/libro/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/libro/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fondo{% endblock %}

{% block body %}{{ include('menu.html.twig', { selectedMenu: 'home'}) }}

    <h1>Edit Fondo</h1>

    {{ include('libro/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('libro_index') }}">back to list</a>

    {{ include('libro/_delete_form.html.twig') }}
{% endblock %}

templates/libro/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fondo index{% endblock %}

{% block body %}
    <h1>Fondo index</h1>


{% for message in app.flashes('Info') %}
    <div class="flash-notice">
        {{ message }}
    </div>
    <script class="flash-notice"> alert("Mensaje nuevo") </script>
{% endfor %}
    <table class="table table-dark table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titulo</th>
                <th>Autor</th>
                <th>ISBN</th>
                <th>Edicion</th>
                <th>Publicacion</th>
                <th>Categoria</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fondo in fondos %}
            <tr>
                <td>{{ fondo.id }}</td>
                <td>{{ fondo.Titulo }}</td>
                {%  for autor in fondo.autor %}
                <td>{{ autor.nombre }}</td>
                {% endfor %}
                <td>{{ fondo.ISBN }}</td>
                <td>{{ fondo.edicion }}</td>
                <td>{{ fondo.publicacion }}</td>
                <td>{{ fondo.categoria }}</td>
                <td>
                    <a href="{{ path('libro_show', {'id': fondo.id}) }}">show</a>
                    <a href="{{ path('libro_edit', {'id': fondo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('libro_new') }}">Create new</a>
{% endblock %}

templates/libro/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fondo{% endblock %}

{% block body %}{{ include('menu.html.twig', { selectedMenu: 'home'}) }}

    <h1>Create new Fondo</h1>

    {{ include('libro/_form.html.twig') }}

    <a href="{{ path('libro_index') }}">back to list</a>
{% endblock %}

templates/libro/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fondo{% endblock %}

{% block body %}{{ include('menu.html.twig', { selectedMenu: 'home'}) }}

    <h1>Fondo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fondo.id }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ fondo.Titulo }}</td>
            </tr>
            <tr>
                <th>ISBN</th>
                <td>{{ fondo.ISBN }}</td>
            </tr>
            <tr>
                <th>Edicion</th>
                <td>{{ fondo.edicion }}</td>
            </tr>
             <tr>
                <th>Edicion</th>
                <td>{{ fondo.editorial }}</td>
            </tr>
            <tr>
                <th>Publicacion</th>
                <td>{{ fondo.publicacion }}</td>
            </tr>
            <tr>
                <th>Categoria</th>
                <td>{{ fondo.categoria }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('libro_index') }}">back to list</a>

    <a href="{{ path('libro_edit', {'id': fondo.id}) }}">edit</a>

    {{ include('libro/_delete_form.html.twig') }}
{% endblock %}